#!/usr/bin/env bash
# HiDevLab WebIDE 开机脚本：每次控制台「启动」环境并进入 WebIDE 后跑一次。
# 权威说明：docs/engineering/HiDevLab-WebIDE操作手册.md
#
# 用法（在 WebIDE 终端）：
#   bash /workspace/ascendc/scripts/hidevlab/webide_boot.sh
#
# 可选环境变量：
#   HIDEVLAB_BRANCH   要检出的分支（默认：当前分支，否则 main）
#   HIDEVLAB_PULL=0   跳过 git fetch/pull
#   HIDEVLAB_SOC      仅打印建议 -v（默认 Ascend910B3）
#   ASCEND_DEVICE_ID  逻辑设备号（默认 0；勿填物理 davinci 号）
#
# 本脚本：配环境 + 体检 + 写可 source 的 env 文件；不发起 SSH，也不让 Cloud Agent 自动连上。
set -euo pipefail

WORKTREE="${HIDEVLAB_WORKTREE:-/workspace/ascendc}"
SOC_VERSION="${HIDEVLAB_SOC:-Ascend910B3}"
DEVICE_ID="${ASCEND_DEVICE_ID:-0}"
DO_PULL="${HIDEVLAB_PULL:-1}"
ENV_FILE="${HIDEVLAB_ENV_FILE:-/workspace/hidevlab_env.sh}"

echo "===== HiDevLab WebIDE boot ====="
echo "time=$(date -u +%Y-%m-%dT%H:%M:%SZ) host=$(hostname)"

if [[ ! -d "${WORKTREE}/.git" ]]; then
  echo "ERROR: 未找到 ${WORKTREE}/.git"
  echo "请先 clone，例如："
  echo "  cd /workspace && git clone https://github.com/bigorange1024/ascendc.git ascendc"
  exit 1
fi

cd "${WORKTREE}"

if [[ -z "${HIDEVLAB_BRANCH:-}" ]]; then
  if git rev-parse --abbrev-ref HEAD >/dev/null 2>&1; then
    HIDEVLAB_BRANCH="$(git rev-parse --abbrev-ref HEAD)"
  else
    HIDEVLAB_BRANCH="main"
  fi
fi

if [[ "${DO_PULL}" != "0" ]]; then
  echo "--- git: ${HIDEVLAB_BRANCH} ---"
  git fetch origin "${HIDEVLAB_BRANCH}"
  git checkout "${HIDEVLAB_BRANCH}"
  git pull --ff-only origin "${HIDEVLAB_BRANCH}"
else
  echo "--- git pull skipped (HIDEVLAB_PULL=0) ---"
fi

echo "git=$(git rev-parse --short HEAD) branch=$(git rev-parse --abbrev-ref HEAD)"

CANN_SET_ENV=""
for cand in \
  /usr/local/Ascend/cann/set_env.sh \
  /usr/local/Ascend/ascend-toolkit/set_env.sh \
  /usr/local/Ascend/cann-9.1.0/set_env.sh
do
  if [[ -f "${cand}" ]]; then
    CANN_SET_ENV="${cand}"
    break
  fi
done
if [[ -z "${CANN_SET_ENV}" ]]; then
  echo "ERROR: 未找到 Ascend set_env.sh"
  exit 1
fi

# shellcheck disable=SC1090
source "${CANN_SET_ENV}"
export LD_LIBRARY_PATH="/usr/local/Ascend/driver/lib64:/usr/local/Ascend/driver/lib64/driver:/usr/local/Ascend/driver/lib64/common:${LD_LIBRARY_PATH:-}"
export ASCEND_DEVICE_ID="${DEVICE_ID}"
export CANNLAB=1
export CMAKE_BUILD_JOBS="${CMAKE_BUILD_JOBS:-8}"
export HIDEVLAB=1

# 持久化到可 source 文件（供同一 WebIDE 会话后续终端用）
cat > "${ENV_FILE}" <<EOF
# generated by webide_boot.sh — source 此文件即可恢复本会话 Ascend/NPU 环境
# shellcheck disable=SC1090
source '${CANN_SET_ENV}'
export LD_LIBRARY_PATH=/usr/local/Ascend/driver/lib64:/usr/local/Ascend/driver/lib64/driver:/usr/local/Ascend/driver/lib64/common:\${LD_LIBRARY_PATH:-}
export ASCEND_DEVICE_ID=${DEVICE_ID}
export CANNLAB=1
export HIDEVLAB=1
export CMAKE_BUILD_JOBS=\${CMAKE_BUILD_JOBS:-8}
export HIDEVLAB_WORKTREE='${WORKTREE}'
export HIDEVLAB_SOC='${SOC_VERSION}'
EOF
chmod 644 "${ENV_FILE}"

echo "--- probe ---"
echo "CANN_SET_ENV=${CANN_SET_ENV}"
command -v ccec >/dev/null && ccec --version 2>&1 | head -2 || echo "WARN: ccec missing"
echo -n "davinci nodes: "; ls /dev/davinci[0-9]* 2>/dev/null || echo "(none)"
if command -v npu-smi >/dev/null; then
  npu-smi info 2>&1 | head -20
else
  echo "WARN: npu-smi missing"
fi

echo
echo "===== boot OK ====="
echo "env file: source ${ENV_FILE}"
echo "逻辑设备 ASCEND_DEVICE_ID=${DEVICE_ID}（物理 /dev/davinciN 可能是 5/7/…，勿填进 SetDevice）"
echo "建议 SoC: -v ${SOC_VERSION}"
echo
echo "下一刀冒烟（可选，整块粘贴）："
echo "  source ${ENV_FILE}"
echo "  cd ${WORKTREE}/ascendc-tests/add_custom"
echo "  ASCEND_DEVICE_ID=${DEVICE_ID} CANNLAB=1 CMAKE_BUILD_JOBS=\${CMAKE_BUILD_JOBS} \\"
echo "    bash run.sh -r npu -v ${SOC_VERSION}"
echo
echo "或让 Agent 再出配方：bash scripts/hidevlab/webide_recipe.sh add_custom"
echo "说明: 本脚本不打通 Cloud Agent 远程 SSH；协作仍是 WebIDE 粘贴配方。"
