#!/usr/bin/env bash
# HiDevLab WebIDE 开机脚本：每次控制台「启动」后进 WebIDE 跑一次。
# 权威说明：docs/engineering/HiDevLab-WebIDE操作手册.md
#
# 用法：
#   bash /workspace/ascendc/scripts/hidevlab/webide_boot.sh
#
# 默认不做 git pull（避免 GitHub 网络卡住）。需要更新代码时：
#   HIDEVLAB_PULL=1 bash /workspace/ascendc/scripts/hidevlab/webide_boot.sh
#
# 可选：HIDEVLAB_BRANCH / ASCEND_DEVICE_ID / HIDEVLAB_SOC / HIDEVLAB_GIT_TIMEOUT_SEC
set -euo pipefail

WORKTREE="${HIDEVLAB_WORKTREE:-/workspace/ascendc}"
SOC_VERSION="${HIDEVLAB_SOC:-Ascend910B3}"
DEVICE_ID="${ASCEND_DEVICE_ID:-0}"
DO_PULL="${HIDEVLAB_PULL:-0}"
GIT_TIMEOUT_SEC="${HIDEVLAB_GIT_TIMEOUT_SEC:-45}"
ENV_FILE="${HIDEVLAB_ENV_FILE:-/workspace/hidevlab_env.sh}"

echo "===== HiDevLab WebIDE boot ====="
echo "time=$(date -u +%Y-%m-%dT%H:%M:%SZ) host=$(hostname)"

if [[ ! -d "${WORKTREE}/.git" ]]; then
  echo "ERROR: 未找到 ${WORKTREE}/.git — 请先 clone 到 ${WORKTREE}"
  exit 1
fi
cd "${WORKTREE}"

# 1) 先配环境（不碰网络）
CANN_SET_ENV=""
for cand in \
  /usr/local/Ascend/cann/set_env.sh \
  /usr/local/Ascend/ascend-toolkit/set_env.sh \
  /usr/local/Ascend/cann-9.1.0/set_env.sh
do
  if [[ -f "${cand}" ]]; then CANN_SET_ENV="${cand}"; break; fi
done
[[ -n "${CANN_SET_ENV}" ]] || { echo "ERROR: 未找到 Ascend set_env.sh"; exit 1; }

# shellcheck disable=SC1090
source "${CANN_SET_ENV}"
export LD_LIBRARY_PATH="/usr/local/Ascend/driver/lib64:/usr/local/Ascend/driver/lib64/driver:/usr/local/Ascend/driver/lib64/common:${LD_LIBRARY_PATH:-}"
export ASCEND_DEVICE_ID="${DEVICE_ID}"
export CANNLAB=1
export CMAKE_BUILD_JOBS="${CMAKE_BUILD_JOBS:-8}"
export HIDEVLAB=1

cat > "${ENV_FILE}" <<EOF
# generated by webide_boot.sh
source '${CANN_SET_ENV}'
export LD_LIBRARY_PATH=/usr/local/Ascend/driver/lib64:/usr/local/Ascend/driver/lib64/driver:/usr/local/Ascend/driver/lib64/common:\${LD_LIBRARY_PATH:-}
export ASCEND_DEVICE_ID=${DEVICE_ID}
export CANNLAB=1
export HIDEVLAB=1
export CMAKE_BUILD_JOBS=\${CMAKE_BUILD_JOBS:-8}
export HIDEVLAB_WORKTREE='${WORKTREE}'
export HIDEVLAB_SOC='${SOC_VERSION}'
EOF

echo "--- env ---"
echo "CANN_SET_ENV=${CANN_SET_ENV}"
echo "ASCEND_DEVICE_ID=${ASCEND_DEVICE_ID}"
command -v ccec >/dev/null && ccec --version 2>&1 | head -2 || echo "WARN: ccec missing"
echo -n "davinci: "; ls /dev/davinci[0-9]* 2>/dev/null || echo "(none)"
if command -v npu-smi >/dev/null; then
  if command -v timeout >/dev/null; then
    timeout 20 npu-smi info 2>&1 | head -20 || echo "WARN: npu-smi timeout/fail"
  else
    npu-smi info 2>&1 | head -20 || true
  fi
else
  echo "WARN: npu-smi missing"
fi

echo "git=$(git rev-parse --short HEAD 2>/dev/null || echo '?') branch=$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo '?')"

# 2) 可选 git（带超时；默认关闭）
if [[ "${DO_PULL}" == "1" ]]; then
  if [[ -z "${HIDEVLAB_BRANCH:-}" ]]; then
    HIDEVLAB_BRANCH="$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo main)"
  fi
  echo "--- git pull (${HIDEVLAB_BRANCH}, timeout=${GIT_TIMEOUT_SEC}s) ---"
  export GIT_TERMINAL_PROMPT=0
  if command -v timeout >/dev/null; then
    timeout "${GIT_TIMEOUT_SEC}" git fetch origin "${HIDEVLAB_BRANCH}" \
      && git checkout "${HIDEVLAB_BRANCH}" \
      && timeout "${GIT_TIMEOUT_SEC}" git pull --ff-only origin "${HIDEVLAB_BRANCH}" \
      || echo "WARN: git 超时或失败，继续用本地树（可稍后手动 git pull）"
  else
    git fetch origin "${HIDEVLAB_BRANCH}" \
      && git checkout "${HIDEVLAB_BRANCH}" \
      && git pull --ff-only origin "${HIDEVLAB_BRANCH}" \
      || echo "WARN: git 失败，继续用本地树"
  fi
  echo "git=$(git rev-parse --short HEAD) branch=$(git rev-parse --abbrev-ref HEAD)"
else
  echo "--- git pull skipped（默认；需要时 HIDEVLAB_PULL=1）---"
fi

echo "===== boot OK ====="
echo "source ${ENV_FILE}"
