#!/usr/bin/env bash
# HiDevLab WebIDE 开机脚本（人侧每次启动后跑一次）
# 默认不访问 GitHub（该环境常连不上 github.com:443）。
# 建议落盘路径（不依赖仓库拉取）：/workspace/hidevlab_boot.sh
# 仓库副本：scripts/hidevlab/webide_boot.sh
set -euo pipefail

WORKTREE="${HIDEVLAB_WORKTREE:-/workspace/ascendc}"
SOC_VERSION="${HIDEVLAB_SOC:-Ascend910B3}"
DEVICE_ID="${ASCEND_DEVICE_ID:-0}"
DO_PULL="${HIDEVLAB_PULL:-0}"
GIT_TIMEOUT_SEC="${HIDEVLAB_GIT_TIMEOUT_SEC:-20}"
ENV_FILE="${HIDEVLAB_ENV_FILE:-/workspace/hidevlab_env.sh}"

echo "===== HiDevLab WebIDE boot ====="
echo "time=$(date -u +%Y-%m-%dT%H:%M:%SZ) host=$(hostname)"

CANN_SET_ENV=""
for cand in \
  /usr/local/Ascend/cann/set_env.sh \
  /usr/local/Ascend/ascend-toolkit/set_env.sh \
  /usr/local/Ascend/cann-9.1.0/set_env.sh
do
  if [[ -f "${cand}" ]]; then CANN_SET_ENV="${cand}"; break; fi
done
if [[ -z "${CANN_SET_ENV}" ]]; then
  echo "ERROR: 未找到 Ascend set_env.sh"
  exit 1
fi

# Ascend set_env.sh 会读未定义的 LD_LIBRARY_PATH 等；短暂关闭 nounset
set +u
# shellcheck disable=SC1090
source "${CANN_SET_ENV}"
set -u
export LD_LIBRARY_PATH="/usr/local/Ascend/driver/lib64:/usr/local/Ascend/driver/lib64/driver:/usr/local/Ascend/driver/lib64/common:${LD_LIBRARY_PATH:-}"
export ASCEND_DEVICE_ID="${DEVICE_ID}"
export CANNLAB=1
export CMAKE_BUILD_JOBS="${CMAKE_BUILD_JOBS:-8}"
export HIDEVLAB=1
# 镜像自带 python3.12（含 numpy）；系统 /usr/bin/python3 常无 numpy → gen_data 挂
if [[ -d /usr/local/python3.12.13/bin ]]; then
  export PATH="/usr/local/python3.12.13/bin:${PATH}"
fi

cat > "${ENV_FILE}" <<EOF
# generated by hidevlab_boot / webide_boot.sh
source '${CANN_SET_ENV}'
export LD_LIBRARY_PATH=/usr/local/Ascend/driver/lib64:/usr/local/Ascend/driver/lib64/driver:/usr/local/Ascend/driver/lib64/common:\${LD_LIBRARY_PATH:-}
export ASCEND_DEVICE_ID=${DEVICE_ID}
export CANNLAB=1
export HIDEVLAB=1
export CMAKE_BUILD_JOBS=\${CMAKE_BUILD_JOBS:-8}
export HIDEVLAB_WORKTREE='${WORKTREE}'
export HIDEVLAB_SOC='${SOC_VERSION}'
if [ -d /usr/local/python3.12.13/bin ]; then
  export PATH=/usr/local/python3.12.13/bin:\${PATH}
fi
EOF

echo "--- env ---"
echo "CANN_SET_ENV=${CANN_SET_ENV}"
echo "ASCEND_DEVICE_ID=${ASCEND_DEVICE_ID}"
if command -v ccec >/dev/null; then ccec --version 2>&1 | head -2; else echo "WARN: ccec missing"; fi
echo -n "davinci: "; ls /dev/davinci[0-9]* 2>/dev/null || echo "(none)"
if command -v npu-smi >/dev/null; then
  if command -v timeout >/dev/null; then
    timeout 20 npu-smi info 2>&1 | head -20 || echo "WARN: npu-smi timeout/fail"
  else
    npu-smi info 2>&1 | head -20 || true
  fi
else
  echo "WARN: npu-smi missing"
fi

if [[ -d "${WORKTREE}/.git" ]]; then
  echo "git=$(git -C "${WORKTREE}" rev-parse --short HEAD 2>/dev/null || echo '?') branch=$(git -C "${WORKTREE}" rev-parse --abbrev-ref HEAD 2>/dev/null || echo '?')"
else
  echo "WARN: ${WORKTREE} 无 git 树"
fi

if [[ "${DO_PULL}" == "1" && -d "${WORKTREE}/.git" ]]; then
  echo "--- git pull (timeout=${GIT_TIMEOUT_SEC}s) ---"
  export GIT_TERMINAL_PROMPT=0
  BRANCH="${HIDEVLAB_BRANCH:-$(git -C "${WORKTREE}" rev-parse --abbrev-ref HEAD 2>/dev/null || echo main)}"
  if command -v timeout >/dev/null; then
    timeout "${GIT_TIMEOUT_SEC}" git -C "${WORKTREE}" fetch origin "${BRANCH}" \
      && git -C "${WORKTREE}" checkout "${BRANCH}" \
      && timeout "${GIT_TIMEOUT_SEC}" git -C "${WORKTREE}" pull --ff-only origin "${BRANCH}" \
      || echo "WARN: git 失败/超时（本环境常无法访问 GitHub），继续用本地树"
  else
    echo "WARN: 无 timeout 命令，跳过 git（避免挂死）"
  fi
else
  echo "--- git pull skipped（默认；机上常无法访问 GitHub）---"
fi

echo "===== boot OK ====="
echo "env: source ${ENV_FILE}"
