#ifndef DECOMPRESS_D_CONFIG_HPP
#define DECOMPRESS_D_CONFIG_HPP

#ifndef F203_DECOMPRESS_D
#define F203_DECOMPRESS_D 4
#endif

#ifndef DECOMPRESS_D_VEC
#define DECOMPRESS_D_VEC 1
#endif

#if F203_DECOMPRESS_D != 4 && F203_DECOMPRESS_D != 10
#error "F203_DECOMPRESS_D must be 4 or 10"
#endif

#endif
