if(EXISTS ${ASCEND_CANN_PACKAGE_PATH}/compiler/tikcpp/ascendc_kernel_cmake)
    set(ASCENDC_CMAKE_DIR ${ASCEND_CANN_PACKAGE_PATH}/compiler/tikcpp/ascendc_kernel_cmake)
elseif(EXISTS ${ASCEND_CANN_PACKAGE_PATH}/tools/tikcpp/ascendc_kernel_cmake)
    set(ASCENDC_CMAKE_DIR ${ASCEND_CANN_PACKAGE_PATH}/tools/tikcpp/ascendc_kernel_cmake)
else()
    message(FATAL_ERROR "ascendc_kernel_cmake not found under ${ASCEND_CANN_PACKAGE_PATH}")
endif()
include(${ASCENDC_CMAKE_DIR}/ascendc.cmake)

set(_CBD_DEFS F203_CBD_BLOCK_DIM=${F203_CBD_BLOCK_DIM})
if(CBD_P0_SCALAR STREQUAL "ON")
    list(APPEND _CBD_DEFS F203_CBD_ETA2_P0_SCALAR=1)
endif()
if(CBD_P1A_SCALAR_IO STREQUAL "ON")
    list(APPEND _CBD_DEFS F203_CBD_ETA2_P1A_SCALAR_IO=1)
endif()

ascendc_library(ascendc_kernels_${RUN_MODE} SHARED ${KERNEL_FILES})
ascendc_include_directories(ascendc_kernels_${RUN_MODE} PRIVATE ${TEST_ROOT})
ascendc_compile_definitions(ascendc_kernels_${RUN_MODE} PRIVATE ${_CBD_DEFS})
